### ISSUE TITLE
Few Improvement

### ISSUE THREAD

**Issue by faizanayubi** [Swiftintern/PlacementPapers#5]
1. Add User Registration see Readme for api url
2. Change App name to "placement papers" and add app icon
3. Improve Organization page UI
4. Add loading image when page is loaded like as attached
   ![1205048274_ajax-loader-white](https://cloud.githubusercontent.com/assets/4982023/8503637/121241b6-21e0-11e5-88f5-81080ee52f92.gif)
5. Update home page like as shown 
   ![1450199_774421239294756_5456190965961820866_n](https://cloud.githubusercontent.com/assets/4982023/8503667/67d98046-21e0-11e5-8d0a-fb4f2070a317.jpg)
6. Add google analytics to app(your email id added)
7. Remove white background organization paper listing..
   ![20150703105059](https://cloud.githubusercontent.com/assets/4982023/8503731/9a208422-21e1-11e5-8291-f9732929727d.jpg)

**Comment by chhavip** [comment]
App name changed
Google Analytics added
Changed the look of home screen
