### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by faizanayubi** [Swiftintern/PlacementPapers#8]
Make a link to share feedback and rate app on playstore
Create a about page with following content
if possible change font of the entire app

"This app has been created and maintained by Swiftintern.com, it make sharing Placement Experience fun. Share any suggestions ideas to us at info@swiftintern.com, we would glad to hear that, if you want to join us to make this app better send your resume to info@swiftintern.com
More to be coming soon.

SwiftIntern is the India's largest student-focused internship portal, bringing students, employers and higher education institutions together in one centralized location. Swiftintern.com provides a wide variety of interactive tools and services to enable every student, employer and educator to better understand and optimize internship opportunities, enabling businesses to identify the best job candidates and for students to develop the real-world skills they will need upon graduation."

**Comment by faizanayubi** [comment]
Move the files outside of swiftintern folder after completion

**Comment by faizanayubi** [comment]
At login form 
put app logo above name field
Put loading icon and disable submit button after first click

**Comment by faizanayubi** [comment]
Show message "No internet connection" instead of "error something went wrong" on first registration screen
improve Register Button(make it round by edges)

Add option to delete saved paper

and improve about page make the background simple

**Comment by chhavip** [comment]
All done so far.
